# Generated by Django 3.2.25 on 2025-05-30 10:22

from django.db import migrations, models
import reviews.validators


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20250529_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[reviews.validators.check_username], verbose_name='Логин'),
        ),
    ]
